# Generated by Django 4.1.5 on 2023-02-03 13:00

from django.db import migrations, models
import django.db.models.deletion
import home.flexblocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [("wagtailcore", "0078_referenceindex")]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "flexcomponents",
                    wagtail.fields.StreamField(
                        [
                            (
                                "slideshow_top",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "is_visible",
                                            wagtail.blocks.BooleanBlock(
                                                default=True, label="Visible"
                                            ),
                                        ),
                                        (
                                            "slides",
                                            wagtail.blocks.ListBlock(
                                                home.flexblocks.Slide,
                                                collapsed=True,
                                                label="Slides",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "profile",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "first_name",
                                            wagtail.blocks.CharBlock(
                                                label="First name", max_length=255
                                            ),
                                        ),
                                        (
                                            "last_name",
                                            wagtail.blocks.CharBlock(
                                                label="Last name", max_length=255
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image", required=False
                                            ),
                                        ),
                                        (
                                            "job",
                                            wagtail.blocks.CharBlock(
                                                label="Job", max_length=255, required=False
                                            ),
                                        ),
                                        (
                                            "intro",
                                            wagtail.blocks.TextBlock(
                                                blank=True,
                                                label="Intro",
                                                max_length=300,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "company",
                                            wagtail.blocks.CharBlock(
                                                blank=True,
                                                label="Company",
                                                max_length=255,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "email",
                                            wagtail.blocks.EmailBlock(
                                                label="Email", max_length=254, required=False
                                            ),
                                        ),
                                        (
                                            "phone",
                                            wagtail.blocks.CharBlock(
                                                label="Phone", max_length=255, required=False
                                            ),
                                        ),
                                        (
                                            "instagram",
                                            wagtail.blocks.URLBlock(
                                                help_text="Instagram URL", required=False
                                            ),
                                        ),
                                        (
                                            "facebook",
                                            wagtail.blocks.URLBlock(
                                                help_text="Facebook URL", required=False
                                            ),
                                        ),
                                        (
                                            "twitter",
                                            wagtail.blocks.URLBlock(
                                                help_text="Twitter URL", required=False
                                            ),
                                        ),
                                        (
                                            "youtube",
                                            wagtail.blocks.URLBlock(
                                                help_text="YouTube URL", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "cta",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                label="Heading", max_length=255
                                            ),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.blocks.CharBlock(
                                                label="Subheading", max_length=255, required=False
                                            ),
                                        ),
                                        (
                                            "content",
                                            wagtail.blocks.RichTextBlock(
                                                features=["bold", "italic", "ul"],
                                                label="Content",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image", required=False
                                            ),
                                        ),
                                        (
                                            "link_page",
                                            wagtail.blocks.PageChooserBlock(
                                                label="Page", required=False
                                            ),
                                        ),
                                        (
                                            "link_url",
                                            wagtail.blocks.URLBlock(label="Url", required=False),
                                        ),
                                        (
                                            "link_text",
                                            wagtail.blocks.CharBlock(
                                                label="Link text", max_length=255, required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "services",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                label="Heading", max_length=255, required=False
                                            ),
                                        ),
                                        (
                                            "services",
                                            wagtail.blocks.ListBlock(
                                                home.flexblocks.Service, collapsed=True, label=" "
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "products",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                label="Heading", max_length=255, required=False
                                            ),
                                        ),
                                        (
                                            "products",
                                            wagtail.blocks.ListBlock(
                                                home.flexblocks.Product, collapsed=True, label=" "
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "announcements",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                label="Heading", max_length=255, required=False
                                            ),
                                        ),
                                        (
                                            "announcements",
                                            wagtail.blocks.ListBlock(
                                                home.flexblocks.Announcement,
                                                collapsed=True,
                                                label=" ",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "recent_blog_pages",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                label="Heading", max_length=255, required=False
                                            ),
                                        ),
                                        (
                                            "number_of_pages",
                                            wagtail.blocks.IntegerBlock(
                                                default=1,
                                                label="Number of pages",
                                                max_value=10,
                                                min_value=1,
                                                required=True,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "testimonials",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                label="Heading", max_length=255, required=False
                                            ),
                                        ),
                                        (
                                            "testimonials",
                                            wagtail.blocks.ListBlock(home.flexblocks.Testimonial),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={"verbose_name": "Homepage", "verbose_name_plural": "Homepage"},
            bases=("wagtailcore.page",),
        )
    ]
