# Generated by Django 4.1.5 on 2023-02-03 13:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [("wagtailcore", "0078_referenceindex")]

    operations = [
        migrations.CreateModel(
            name="FlexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "flexcomponents",
                    wagtail.fields.StreamField(
                        [
                            (
                                "short_text",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(
                                                max_length=255, required=False
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "long_text",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.TextBlock(
                                                max_length=500, required=False
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "richtext",
                                wagtail.blocks.StructBlock(
                                    [("text", wagtail.blocks.RichTextBlock(required=False))]
                                ),
                            ),
                        ],
                        use_json_field=True,
                    ),
                ),
            ],
            options={"verbose_name": "Flex page", "verbose_name_plural": "Flex page"},
            bases=("wagtailcore.page",),
        )
    ]
