# Generated by Django 4.1.5 on 2023-02-03 13:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("wagtailcore", "0078_referenceindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("site_name", models.CharField(blank=True, max_length=255)),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header",
                "verbose_name_plural": "Header",
                "unique_together": {("translation_key", "locale")},
            },
        ),
        migrations.CreateModel(
            name="HeaderMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("link_title", models.CharField(blank=True, max_length=50, null=True)),
                ("link_url", models.URLField(blank=True, max_length=500, null=True)),
                ("open_in_new_tab", models.BooleanField(blank=True, default=False)),
                (
                    "submenu_title",
                    models.CharField(
                        blank=True, help_text="Submenu title", max_length=50, null=True
                    ),
                ),
                (
                    "show_when",
                    models.CharField(
                        choices=[
                            ("always", "Always"),
                            ("logged_in", "When logged in"),
                            ("not_logged_in", "When not logged in"),
                        ],
                        default="always",
                        max_length=15,
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                    ),
                ),
                (
                    "parent",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="header_menu_items",
                        to="header.header",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header menu item",
                "verbose_name_plural": "Header menu items",
                "ordering": ["sort_order"],
                "unique_together": {("translation_key", "locale")},
            },
        ),
    ]
