# Generated by Django 4.1.5 on 2023-02-03 13:00

import about.flexblocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [("wagtailcore", "0078_referenceindex")]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "flexcomponents",
                    wagtail.fields.StreamField(
                        [
                            (
                                "profile",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "first_name",
                                            wagtail.blocks.CharBlock(
                                                label="First name", max_length=255
                                            ),
                                        ),
                                        (
                                            "last_name",
                                            wagtail.blocks.CharBlock(
                                                label="Last name", max_length=255
                                            ),
                                        ),
                                        (
                                            "job",
                                            wagtail.blocks.CharBlock(
                                                label="Job", max_length=255, required=False
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image", required=False
                                            ),
                                        ),
                                        (
                                            "intro",
                                            wagtail.blocks.TextBlock(
                                                blank=True,
                                                label="Intro",
                                                max_length=500,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "company",
                                            wagtail.blocks.CharBlock(
                                                blank=True,
                                                label="Company",
                                                max_length=255,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "email",
                                            wagtail.blocks.EmailBlock(
                                                label="Email", max_length=254, required=False
                                            ),
                                        ),
                                        (
                                            "phone",
                                            wagtail.blocks.CharBlock(
                                                label="Phone", max_length=255, required=False
                                            ),
                                        ),
                                        (
                                            "instagram",
                                            wagtail.blocks.URLBlock(
                                                help_text="Instagram URL",
                                                label="Instagram",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "facebook",
                                            wagtail.blocks.URLBlock(
                                                help_text="Facebook URL",
                                                label="Facebook",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "twitter",
                                            wagtail.blocks.URLBlock(
                                                help_text="Twitter URL",
                                                label="Twitter",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "youtube",
                                            wagtail.blocks.URLBlock(
                                                help_text="YouTube URL",
                                                label="YouTube",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "employment_history",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                label="Heading", max_length=255, required=False
                                            ),
                                        ),
                                        (
                                            "employment_history",
                                            wagtail.blocks.ListBlock(
                                                about.flexblocks.Employment,
                                                collapsed=True,
                                                label="Employment history",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "university_education",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                label="Heading", max_length=255
                                            ),
                                        ),
                                        (
                                            "university_education",
                                            wagtail.blocks.ListBlock(
                                                about.flexblocks.University,
                                                collapsed=True,
                                                label="University education",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "richtext",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                max_length=255, required=False
                                            ),
                                        ),
                                        ("richtext", wagtail.blocks.RichTextBlock(required=False)),
                                    ]
                                ),
                            ),
                        ],
                        use_json_field=True,
                    ),
                ),
            ],
            options={"verbose_name": "About page", "verbose_name_plural": "About page"},
            bases=("wagtailcore.page",),
        )
    ]
