# Generated by Django 4.1.6 on 2023-02-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("wagtailcore", "0078_referenceindex"), ("site_settings", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="contact_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.page",
            ),
        )
    ]
