# Generated by Django 4.1.5 on 2023-02-03 13:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("wagtailcore", "0078_referenceindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                )
            ],
            options={"verbose_name": "Footer", "verbose_name_plural": "Footer"},
        ),
        migrations.CreateModel(
            name="FooterMenuBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("heading", models.CharField(blank=True, max_length=255)),
                ("heading_tr", models.CharField(blank=True, max_length=255, null=True)),
                ("heading_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "parent",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footer_menu_blocks",
                        to="footer.footer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer menu block",
                "verbose_name_plural": "Footer menu blocks",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="FooterMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("link_title", models.CharField(blank=True, max_length=50, null=True)),
                ("link_title_tr", models.CharField(blank=True, max_length=50, null=True)),
                ("link_title_en", models.CharField(blank=True, max_length=50, null=True)),
                ("link_url", models.URLField(blank=True, max_length=500, null=True)),
                ("open_in_new_tab", models.BooleanField(blank=True, default=False)),
                (
                    "submenu_title",
                    models.CharField(
                        blank=True, help_text="Submenu title", max_length=50, null=True
                    ),
                ),
                (
                    "show_when",
                    models.CharField(
                        choices=[
                            ("always", "Always"),
                            ("logged_in", "When logged in"),
                            ("not_logged_in", "When not logged in"),
                        ],
                        default="always",
                        max_length=15,
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "link_page_en",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "link_page_tr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "parent",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footer_menu_items",
                        to="footer.footermenublock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer menu item",
                "verbose_name_plural": "Footer menu items",
                "ordering": ["sort_order"],
            },
        ),
    ]
